In [2]:
import tensorflow as tf
import numpy as np

tf.__version__

'2.4.0-dev20200828'

In [3]:
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
tf.config.list_physical_devices('GPU')

[]

# Tensor Basics

In [5]:
array = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [6]:
t = tf.constant(array)
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [7]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [8]:
t.shape

TensorShape([3, 3])

# Operations and Reshaping

In [9]:
t = tf.constant([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=tf.float32) 

In [10]:
reshaped_tensor = tf.reshape(t, [1, 12])
reshaped_tensor

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=array([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=float32)>

In [11]:
reshaped_tensor = tf.reshape(t, [2, 6])
reshaped_tensor

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 2., 2.],
       [2., 2., 3., 3., 3., 3.]], dtype=float32)>

In [12]:
reshaped_tensor = tf.reshape(t, [2, 3, 2])
reshaped_tensor

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [2., 2.]],

       [[2., 2.],
        [3., 3.],
        [3., 3.]]], dtype=float32)>

### Squeezing

In [17]:
tf.reshape(t, [1, 12])

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=array([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=float32)>

In [18]:
tf.reshape(t, [1, 12]).shape

TensorShape([1, 12])

In [19]:
tf.squeeze(tf.reshape(t, [1, 12]))

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.], dtype=float32)>

In [20]:
tf.squeeze(tf.reshape(t, [1, 12])).shape

TensorShape([12])

### Flattening

In [21]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    # return tf.squeeze(tf.reshape(t, [1, -1]))
    return t

In [22]:
t = tf.zeros([5, 4])
t

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [23]:
flatten(t)

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)>

### Concatenate

In [24]:
t1 = tf.constant([
    [1, 1],
    [2, 2]
])

t2 = tf.constant([
    [3, 3],
    [4, 4]
])

In [27]:
tf.concat((t1, t2), axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])>

In [29]:
tf.concat((t1, t2), axis=0).shape

TensorShape([4, 2])

In [28]:
tf.concat((t1, t2), axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 3, 3],
       [2, 2, 4, 4]])>

In [30]:
tf.concat((t1, t2), axis=1).shape

TensorShape([2, 4])

## Maths

In [31]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1], 
                 [1, 1]])

print(tf.add(a, b))
print(tf.multiply(a, b))
print(tf.matmul(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [32]:
print(a + b)
print(a * b)
print(a @ b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)
