In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

### Building a simple `Sequential` model

In [4]:
model = Sequential(
    [
        Dense(2, activation='relu', name='layer1'),
        Dense(3, activation='relu', name='layer2'),
        Dense(4, name='layer3')
    ]
)

x = tf.ones((3, 3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.9161597, -0.9332034, -1.5737247, -1.3197713],
       [ 0.9161597, -0.9332034, -1.5737247, -1.3197713],
       [ 0.9161597, -0.9332034, -1.5737247, -1.3197713]], dtype=float32)>

In [5]:
layer1 = Dense(2, activation="relu", name="layer1")
layer2 = Dense(3, activation="relu", name="layer2")
layer3 = Dense(4, name="layer3")

x = tf.ones((3, 3))
# layers are stacked accordingly
y = layer3(layer2(layer1(x)))  
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.17414168, -0.1285467 , -0.79117846, -0.45501158],
       [-0.17414168, -0.1285467 , -0.79117846, -0.45501158],
       [-0.17414168, -0.1285467 , -0.79117846, -0.45501158]],
      dtype=float32)>

In [6]:
model = keras.Sequential(name="seq_model") 
# give your model a cute name

model.add(Dense(2, activation="relu"))
model.add(Dense(3, activation="relu"))
model.add(Dense(4))

x = tf.ones((3, 3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Adding inputs

In [7]:
model = keras.Sequential()
model.add(keras.Input(shape=(4,))) 
# Why (4,) and not 4? 
# Because we want our input to be a Vector (1D Tensor)
model.add(layers.Dense(2, activation="relu"))

In [8]:
model = keras.Sequential()
model.add(layers.Dense(2, activation="relu", input_shape=(4,)))  
# We can specify the input for the Dense layer

### Summary of model

In [9]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________


Understanding the summary:
- Model name: "sequential_2"
- It contains 1 layer of type `Dense`.
- The output shape of the layer is `(None, 2)` which represents `(batch_size, units)`. Since we have not specified `batch_size` it will default to `None`.
- Number of params can be calculate as:
            num_params = output_shape * (input_shape + 1)
            in this case it's 2 x (4 + 1) = 10
- Trainable/non-trainable: specify if these layers/parameters are trainable or not, meaning their weights can be updated through training or not.

In [11]:
from tensorflow.keras.utils import plot_model

plot_model(model)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


## Functional Model

In [12]:
from tensorflow.keras import Input

x_in = Input(shape=(8,))

In [13]:
dense = Dense(64, activation='relu')
x = Dense(10)(x_in)

In [14]:
x_out = Dense(1)(x)

In [16]:
from tensorflow.keras import Model

x_in = Input(shape=(8,))
x = Dense(10)(x_in)
x_out = Dense(1)(x)

model = Model(inputs=x_in, outputs=x_out)
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 8)]               0         
_________________________________________________________________
dense_10 (Dense)             (None, 10)                90        
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 11        
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________
